export const ESTADO_SOCILICUD = {
  PENDIENTE_ADMIN_APP: 'PENDIENTE_ADMIN_APP',
  PENDIENTE_MASTER: 'PENDIENTE_MASTER',
  APROBADO: 'APROBADO',
  DENEGADO: 'DENEGADO'
};

export const ESTADO_COMUN = {
  PENDIENTE: 'PENDIENTE',
  APROBADO: 'APROBADO',
  DENEGADO: 'DENEGADO'
};
